import React from 'react';
import { ShieldCheck } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface LegalModalProps {
  open: boolean;
  onClose: () => void;
}

export default function LegalModal({ open, onClose }: LegalModalProps) {
  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 bg-[#020617]/85 backdrop-blur-md flex items-center justify-center p-3.5 sm:p-6 z-50 overflow-y-auto"
          id="legal-disclaimer-overlay"
        >
          <motion.div
            initial={{ scale: 0.95, y: 15 }}
            animate={{ scale: 1, y: 0 }}
            exit={{ scale: 0.95, y: 10 }}
            className="bg-[#0f172a] border border-rose-500/25 rounded-2xl p-5 sm:p-7 w-full max-w-2xl shadow-2xl relative space-y-5 my-6 leading-relaxed text-slate-200"
            id="legal-disclaimer-card"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-start gap-3.5 pb-4 border-b border-[#1e293b] text-rose-400">
              <div className="p-2.5 bg-rose-950/40 border border-rose-500/30 rounded-2xl shadow-[0_0_15px_rgba(244,63,94,0.15)] flex items-center justify-center shrink-0">
                <ShieldCheck className="w-5 h-5 text-rose-400" />
              </div>
              <div>
                <h4 className="text-sm font-black uppercase tracking-widest font-mono text-rose-400">
                  Liability Disclaimer & Indemnity Agreement
                </h4>
                <p className="text-[10px] text-slate-400 font-medium uppercase font-mono mt-0.5">
                  LABRAT USER TERMS • IN-FORCE SCIENTIFIC PROTECTION
                </p>
              </div>
            </div>

            <div className="bg-[#030712]/60 border border-slate-800 rounded-xl p-4 text-[11px] sm:text-xs text-slate-300 font-mono space-y-4 max-h-[60vh] overflow-y-auto custom-scrollbar" id="legal-agreement-scrollbar-panel">
              <div className="space-y-1">
                <span className="text-rose-400 font-bold tracking-wider block">SECTION 1: NO PROVISION OF MEDICAL ADVICE</span>
                <p className="leading-normal">
                  The software, compiled libraries, and calculator values generated by the labrat platform are developed entirely for educational, historical tracking, and informational laboratory research purposes. They do not constitute the practice of medicine, nursing, clinical pharmacy, or the professional dispensing of medical services or substances.
                </p>
              </div>

              <div className="space-y-1">
                <span className="text-rose-400 font-bold tracking-wider block">SECTION 2: ABSOLUTE INDEMNIFICATION & THE "HOLD HARMLESS" COVENANT</span>
                <p className="leading-normal">
                  By launching and continuing usage of labrat registers, you unconditionally, irrevocably agree to defend, indemnify, and hold harmless the developers, programmers, publishers, webmasters, hosting agencies, and any parent organizations of labrat from any and all liability, damages, litigation costs, medical fees, physiological damage, or fatalities resulting from any action you take using this program.
                </p>
              </div>

              <div className="space-y-1">
                <span className="text-rose-400 font-bold tracking-wider block">SECTION 3: INHERENT EXPERIMENTAL NATURE & RISKS</span>
                <p className="leading-normal">
                  You explicitly acknowledge that biological research, peptide compounding, research chemicals, and endocrine management are associated with severe medical complications, biological contamination, immunological shock, infection, sepsis, and structural toxicity. All formulations, injection volumes, reconstitutions, and protocols logged are recorded at your own peril and absolute personal risk.
                </p>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-3 border-t border-[#1e293b]">
              <p className="text-[10.5px] text-slate-400 text-center sm:text-left">
                Leaving this screen indicates full compliance and execution of these terms.
              </p>
              <div className="flex gap-2 w-full sm:w-auto">
                <button
                  onClick={onClose}
                  className="flex-1 sm:flex-none text-center px-5 py-2.5 bg-rose-500 hover:bg-rose-600 text-white rounded-xl text-xs font-bold transition-all shadow-[0_0_15px_rgba(244,63,94,0.2)] hover:shadow-[0_0_20px_rgba(244,63,94,0.3)] cursor-pointer"
                  id="legal-modal-agree-btn"
                >
                  I Agree & Hold Harmless
                </button>
                <button
                  onClick={onClose}
                  className="px-4 py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl text-xs font-semibold transition"
                  id="legal-modal-close-btn"
                >
                  Close
                </button>
              </div>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
